%% Example of extracting average power feature

level2File = 'studyLevelDerived_description.xml';
levelDerivedDir = 'Z:\Data 3\BCIT_ESS\Level2_256Hz_ASR\Experiment X2 Traffic Complexity';
levelDerivedDirNew = 'Z:\Data 3\BCIT_ESS\Level2_256Hz_feature\averagePower\Experiment X2 Traffic Complexity';

%% Make sure level 2 derived study validates
derivedXMLFile = [levelDerivedDir filesep level2File];
obj = levelDerivedStudy('parentStudyXmlFilePath', derivedXMLFile);

%% Call the average power feature extraction
callbackAndParameters = {@averagePower, ...
                            {'subbands', [0 4; 4 8; 8 12; 12 16; 16 20; 20 24; 24 28; 28 32], ...
                             'filterOrder', 844, ...
                             'windowLength', 1.0, ...
                             'subWindowLength', 0.125, ...
                             'step', 0.125}};    
obj = obj.createLevelDerivedStudy(callbackAndParameters, ...
      'filterDescription', 'Extract average power feature', ...
     'filterLabel', 'average power', 'levelDerivedFolder', levelDerivedDirFeature);
 