function scoreData = getScoreDataStructure() 

scoreData = struct('testFileName', NaN, ...
    'trainFileName', NaN, ...
    'trueLabels', NaN, ...
    'predLabels', NaN, ...
    'finalScores', NaN, ...
    'finalCutoff', NaN, ...
    'initProbs', NaN, ...
    'initCutoff', NaN, ...
    'trainLabels', NaN, ...
    'trainScores', NaN);