function annotData = getAnnotDataStructure()

annotData = struct('testFileName', NaN, 'trainFileNames', NaN, ...
                   'params', NaN, 'classLabel', NaN, ...
                   'trueLabels', NaN, ...
                   'initialCutoffs', NaN', ...
                   'wScores', NaN, 'wmScores', NaN, ...
                   'combinedCutoff', NaN);